In [120]:
import numpy as np

In [121]:
from PIL import Image

In [ ]:
image=Image.open(r'Add_Your_Path_here').convert('L')
img_array= np.array(image)

In [123]:
print('image shape is ', img_array.shape)

image shape is  (720, 860)


In [124]:
img_array

array([[247, 247, 247, ..., 247, 247, 247],
       [247, 247, 247, ..., 247, 247, 247],
       [247, 247, 247, ..., 247, 247, 247],
       ...,
       [247, 247, 247, ..., 247, 247, 247],
       [247, 247, 247, ..., 247, 247, 247],
       [247, 247, 247, ..., 247, 247, 247]], dtype=uint8)

In [ ]:
#You can change your kerner to however you like
kernel=np.array([[3,10,3],[0,0,0],[-3,-10,-3]])
print(kernel)

[[  3  10   3]
 [  0   0   0]
 [ -3 -10  -3]]


In [126]:
output = np.zeros_like(img_array)


rows, cols = img_array.shape

In [127]:
for i in range(1,rows-1):
    for j in range(1,cols-1):
        region = img_array[i-1:i+2, j-1:j+2]
        
        # Element-wise multiplication and sum
        conv_value = np.sum(region * kernel)
        
        # Clip to valid pixel range (0–255)
        output[i, j] = np.clip(conv_value, 0, 255)

In [ ]:
Image.fromarray(output).save("convolved_image55.png")


: 